// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzrd97rA-XsCGEmBVtWtMdlTgbvls6J3s',
    appId: '1:531390213636:web:940dc9736eae319fddcf51',
    messagingSenderId: '531390213636',
    projectId: 'checkmate-9a60c',
    authDomain: 'checkmate-9a60c.firebaseapp.com',
    storageBucket: 'checkmate-9a60c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKb29M0xIdpE4SzA8ojVA4Z_jc4H9AzJc',
    appId: '1:531390213636:android:9bb48c83c388c494ddcf51',
    messagingSenderId: '531390213636',
    projectId: 'checkmate-9a60c',
    storageBucket: 'checkmate-9a60c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnQ6zHKkAfDhXTbbU9c2Ai86QpLLBN4D8',
    appId: '1:531390213636:ios:fbf11966d284b969ddcf51',
    messagingSenderId: '531390213636',
    projectId: 'checkmate-9a60c',
    storageBucket: 'checkmate-9a60c.firebasestorage.app',
    iosBundleId: 'com.example.flutterCheckmate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnQ6zHKkAfDhXTbbU9c2Ai86QpLLBN4D8',
    appId: '1:531390213636:ios:fbf11966d284b969ddcf51',
    messagingSenderId: '531390213636',
    projectId: 'checkmate-9a60c',
    storageBucket: 'checkmate-9a60c.firebasestorage.app',
    iosBundleId: 'com.example.flutterCheckmate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzrd97rA-XsCGEmBVtWtMdlTgbvls6J3s',
    appId: '1:531390213636:web:ddb0bdea851e5b7dddcf51',
    messagingSenderId: '531390213636',
    projectId: 'checkmate-9a60c',
    authDomain: 'checkmate-9a60c.firebaseapp.com',
    storageBucket: 'checkmate-9a60c.firebasestorage.app',
  );
}
